spring:
  application:
    name: 0.0.1-SNAPSHOT
  datasource:
    url: jdbc:postgresql://localhost:5432/sugar_shack_maplr_test
    username: ${USER_DB:postgres}
    password: ${PASSWORD_DB:postgres}
  jackson:
    default-property-inclusion: non_null # null values are not included in JSON output
    date-format: "yyyy-MM-dd'T'HH:mm:ssXXX"
    serialization:
      indent-output: true # pretty print
  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  default:
    tz: "America/Toronto"
  api:
    prefix: "/maple-orders"

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui/index.html
