spring:
  application:
    name: maple-orders-api
  datasource:
    url: jdbc:postgresql://localhost:5432/sugar_shack_maplr_test
    username: ${USER_DB:postgres}
    password: ${PASSWORD_DB:postgres}

  flyway:
    enabled: true
    locations: classpath:db/migration


app:
  default:
    tz: "Europe/Paris"

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui/index.html
